title: Karan Singh Rawat
logo: https://github.com/ksrawat888/ksrawat888.github.io/blob/main/Github%20Profile%20Picture.jpg
description: Data Analytics Portfolio
show_downloads: true
theme: jekyll-theme-minimal
